steps:
  # Build del frontend usando Dockerfile.frontend y pasando VITE_API_BASE al build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.frontend
      - --build-arg
      - VITE_API_BASE=${_VITE_API_BASE}
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/frontend/inmo-veo3-ui
      - .
  # Push a Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/frontend/inmo-veo3-ui

# Logs en Cloud Logging para evitar requisitos extra de SA
options:
  logging: CLOUD_LOGGING_ONLY
