# --- Build stage ---
FROM node:20-alpine AS build
WORKDIR /app

# Instala deps
COPY package*.json ./
RUN npm ci

# Copia el resto del proyecto
COPY . .

# Recibe la base del backend y la expone a Vite
ARG VITE_API_BASE
ENV VITE_API_BASE=${VITE_API_BASE}

# Compila
RUN npm run build

# --- Runtime stage ---
FROM nginx:alpine
# NGINX configuración básica para SPA (history fallback a index.html)
RUN printf 'server {\n  listen 8080;\n  server_name _;\n  root /usr/share/nginx/html;\n  index index.html index.htm;\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n}\n' > /etc/nginx/conf.d/default.conf

# Copiamos el build
COPY --from=build /app/dist/ /usr/share/nginx/html/

EXPOSE 8080
CMD ["nginx","-g","daemon off;"]
